### PR TITLE
Adds publishing jobs

### PR DESCRIPTION
**Pull request by claudiubelu**
Adds the publish_images.yaml workflow, which will run when manually dispatched.

This workflow will pull the latest FINOS Waltz image and publishes it on charmhub and release the latest charm revision with the new image revision.

The following Secrets need to be added (Settings > Actions > New repository secret):

- ``CHARMCRAFT_AUTH``: needed to upload the FINOS Legend images, upload the bundle, release the charms and bundle.
- ``GH_TOKEN``: needed to chain the 2 workflows mentioned above.

### CODE REVIEW

**Review by robmoffat — CHANGES_REQUESTED** [review]
Looks good from @maoo, @TheJuanAndOnly.  

This repo needs moving to finos also, though, right?

Please email help@finos.org to get that done.

**Comment by robmoffat** [comment]
HI @pedroleaoc,

@maoo would like you to send me / help@finos.org some commands to run to set up the Waltz EC2 instance?

thanks,
Rob

**Comment by pedroleaoc** [comment]
P.S.: This will probably not be an issue, but in case the IP table rules are not kept on restart, you can save and load them 

```
# Save the rules to a file 
sudo iptables-save >> iptables.rules

# Apply the rules
sudo iptables-apply iptables.rules
```

**Comment by robmoffat** [comment]
Hi Pedro, 

Got stuck on step 1.

```
[ec2-user@ip-172-31-58-252 ~]$ sudo snap install microk8s --classic
sudo: snap: command not found
```

So, we tried updating `yum`, but `snapd` wasn't available there either. @maoo suggested 

```
sudo amazon-linux-extras install epel
...
Error: Package: snapd-selinux-2.54.4-1.el7.noarch (epel)
           Requires: selinux-policy >= 3.13.1-268.el7_9.2
           Installed: selinux-policy-3.13.1-192.amzn2.6.7.noarc
```

Other details:

``` 
uname -a 
Linux ip-172-31-58-252.ec2.internal 5.10.102-99.473.amzn2.x86_64 #1 SMP Wed Mar 2 19:14:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Any ideas?

thanks

**Comment by robmoffat** [comment]
Can you provide some guidance on Linux AMI, rather than Ubuntu?

**Comment by pedroleaoc** [comment]
Not a problem, Rob!

```
# Add the repository
cd /etc/yum.repos.d && wget https://people.canonical.com/~mvo/snapd/amazon-linux2/snapd-amzn2.repo

# List the repos available (snapd should appear)
yum repolist

# Install snapd
yum install snapd

# If EPEL is enabled (check with `yum repolist`, you might have to specify the version
yum install snapd-2.54.3-1.amzn2.1 

# Restart snapd and reload the deamon
sudo systemctl restart snapd snapd.socket
sudo systemctl daemon-reload
```

After that you should be able to follow the instructions above.

Reference: https://forum.snapcraft.io/t/unofficial-snapd-repository-for-amazon-linux-2/24269/7

**Comment by pedroleaoc** [comment]
And for some reasons the commands are not available directly. You can still do `snap run microk8s status`, for instance.

**Comment by pedroleaoc** [comment]
> This looks fine to me. Don't we need to move this repo to finos?

Yep, @TheJuanAndOnly99 asked to review it before I make the transfer.

**Comment by robmoffat** [comment]
ok, got this far:

```
juju config waltz-ingress service-hostname="<public-waltz-hostname>"
```

@maoo We're going to need a public hostname for this. Assume we go for `Waltz.finos.org` to match the Legend one?

**Comment by pedroleaoc** [comment]
> ok, got this far:
> 
> ```
> juju config waltz-ingress service-hostname="<public-waltz-hostname>"
> ```
> 
> @maoo We're going to need a public hostname for this. Assume we go for `Waltz.finos.org` to match the Legend one?

If you just want to test things, you can use the Amazon's public DNS `ec2-user@ec2-xxxxxx.compute-1.amazonaws.com`. It won't work for HTTPS as letsencrypt blocklists it.

**Comment by robmoffat** [comment]
> > This looks fine to me. Don't we need to move this repo to finos?
> 
> Yep, @TheJuanAndOnly99 asked to review it before I make the transfer.

I'll try and get hold of him this avo, he's away next week

**Pull request merged**
